Attribute VB_Name = "Module1"
Sub CGI_Main()
    Send "Status: 200 OK"
    Send "Content-type: text/html" & vbCrLf
    Send "<HTML><HEAD><TITLE>Hello</TITLE></HEAD>"
    Send "<BODY><BASEFONT FACE=""Verdana,Arial,Helvetica"">"
    Send "<H1>Hello!</H1>"
    Send "This may look like an ordinary web page"
    Send "but it is, in fact generated by a CGI"
    Send "script written in Visual Basic!" & vbCrLf
    Send "And here is the next line of text!"
    Send "</BODY></HTML>"
End Sub
