#include "examplewidget.h"
#include "ui_examplewidget.h"

/**
 * A simple widget to show QTreeWidget
 */
ExampleWidget::ExampleWidget(DescriptionHelper* descriptionHelper,
                             QWidget *parent) :
    QWidget(parent),
    ui(new Ui::ExampleWidget)
{
    ui->setupUi(this);
    // @TODO STEP 6.1
    /*
     * Remove the Q_UNUSED macro.
     * Set the selection mode of the UI's tree widget to single selection.
     * Connect the accepted and rejected signals of the UI's buttonBox
     * to the _accepted and _rejected slots of this instance.
     * Use _descriptionHelper to store descriptionHelper.
     */
    Q_UNUSED(descriptionHelper);
}

ExampleWidget::~ExampleWidget()
{
    delete ui;
}

/**
 * This method has been automatically generated by the Qt Creator
 * by adding a Qt Designer Form Class with
 * File > New File or Project ... > Qt > Qt Designer Form Class
 */
void ExampleWidget::changeEvent(QEvent *e)
{
    QWidget::changeEvent(e);
    switch (e->type()) {
    case QEvent::LanguageChange:
        ui->retranslateUi(this);
        break;
    default:
        break;
    }
}

/**
 * Makes descriptionHelper emit a descriptionWasChanged signal.
 */
void ExampleWidget::_accepted()
{
    // @TODO STEP 6.2
    /*
     * Call descriptionHelper's doDescriptionChange method
     * with proper parameters.
     */
}

/**
 * Makes descriptionHelper emit a descriptionWasNotChanged signal.
 */
void ExampleWidget::_cancelled()
{
    // @TODO STEP 6.2
    // Call descriptionHelper's doCancel method.
}
