######################################################################
# Automatically generated by qmake (2.01a) Sun Jul 5 13:32:14 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /Users/lou/Desktop/qtwebkitextension/

QT += webkit

# Input
HEADERS += testobject.h \
    dialog.h
SOURCES += main.cpp testobject.cpp \
    dialog.cpp

OTHER_FILES +=

RESOURCES += \
    res.qrc

FORMS += \
    dialog.ui
